app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, StringField, SubmitField
from wtforms.validators import Length, DataRequired
from flask_pagedown.fields import PageDownField


class NameForm(FlaskForm):
    name = StringField('What is your name?', validators=[DataRequired()])
    submit = SubmitField('Submit')

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    body = PageDownField("What's on your mind?", validators=[DataRequired()])
    submit = SubmitField('Submit')

class EditProfileForm(FlaskForm):
    name = StringField('Real name', validators=[Length(0, 64)])
    location = StringField('Location', validators=[Length(0, 64)])
    about_me = TextAreaField('About me')
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):
    content = TextAreaField('comment')
    submit = SubmitField('submit')

app/main/blueprint.py
from flask import Blueprint

main = Blueprint('main', __name__)

import views, error_handler

app/main/views.py
from flask import flash, render_template, request, current_app
from flask import session, redirect, url_for
from forms import CommentForm, EditProfileForm, NameForm, PostForm
from blueprint import main
from flask_login import login_required, current_user


@main.route('/debug', methods=['GET', 'POST'])
def debug():
    from entity import Post, User
    from flasky import db
    from werkzeug.security import generate_password_hash

    old = 'q'
    new = '1234'

    user = User.query.offset(0).first()
    names = [ follow.follower_id for follow in user.followers]

    return str(user.username) + str(names) + str(user.followers.count())

@main.route('/init_data')
def init_data():
    from fake import users, posts, comments, follows
    from flasky import db
    db.drop_all()
    db.create_all()
    users()
    posts()
    comments()
    # follows()
    return 'data init successfully'

@main.route('/follow', methods=['POST'])
@login_required
def follow():
    from entity import Post, User
    from flasky import db
    followed_id = request.form.get('followed_id', None)
    followed = User.query.filter_by(id=followed_id).first()
    current_user.follow(followed)
    db.session.commit()
    flash(  'follow successfully.')
    return ''

@main.route('/unfollow', methods=['POST'])
@login_required
def unfollow():
    from entity import Post, User
    from flasky import db
    followed_id = request.form.get('followed_id', None)
    followed = User.query.filter_by(id=followed_id).first()
    current_user.unfollow(followed)
    db.session.commit()
    flash(  'follow successfully.')
    return ''


@main.route('/', methods=['GET', 'POST'])
def index():
    from entity import Post

    form = PostForm()
    if form.validate_on_submit():
        write_post(form)
        return redirect(url_for('.index'))

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['INDEXPOST_PER_PAGE']
    pagination = Post.query.order_by(Post.timestamp.desc()) \
        .paginate(page, per_page=per_page, error_out=False)
    return render_template('index.html', form=form, pagination=pagination)

def write_post(form):
    from entity import Post
    from flasky import db
    post = Post(title=form.title.data,
                body=form.body.data,
                author=current_user._get_current_object())
    db.session.add(post)
    db.session.commit()

@main.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    from entity import Post, User


    form = EditProfileForm()
    if form.validate_on_submit():
        from flasky import db
        profile = {
            'name': form.name.data,
            'location': form.location.data,
            'about_me': form.about_me.data,
        }
        User.query.filter_by(username=current_user.username).update(profile)
        db.session.commit()
        flash('Your profile has been updated.')
        return redirect(url_for('.user', username=current_user.username))
    form.name.data = current_user.name
    form.location.data = current_user.location
    form.about_me.data = current_user.about_me
    return render_template('edit_profile.html', form=form)


@main.route('/user/<username>')
def user(username):
    from entity import Post, User
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['USERPOST_PER_PAGE']
    pagination = user.posts.order_by(Post.timestamp.desc())\
        .paginate(page, per_page=per_page, error_out=False)
    return render_template('user.html', user=user, pagination=pagination)


@main.route('/post', methods=['GET', 'POST'])
@main.route('/post/<post_id>', methods=['GET', 'POST'])
def post(post_id):
    from entity import Post, Comment
    post = Post.query.filter_by(id=post_id).first()
    form = CommentForm()

    comments = Comment.query.filter_by(post_id=post_id).order_by(Comment.timestamp)
    comment_count = current_app.config['FLASKY_COMMENTS_PER_PAGE']
    page = request.args.get('page', 1, type=int)
    pagination = comments.paginate(page, error_out=False, per_page=comment_count)
    return render_template('post.html', post=post, form=form,
        pagination=pagination)

@main.route('/comment', methods=['GET', 'POST'])
def comment():
    form = CommentForm()
    submit_comment(form)
    return ''

def submit_comment(form):
    from flasky import db
    from entity import Post, Comment, User

    post_id = request.args.get('post_id', None)
    target_id = request.args.get('target_id', None)
    post = Post.query.filter_by(id=post_id).first()
    target = User.query.filter_by(id=target_id).first()
    comment = Comment(body=form.content.data,
                      post=post,
                      author=current_user,
                      target=target)
    db.session.add(comment)
    db.session.commit()
    flash('comment successfully.')


@main.route('/index')
def index1():
    return 'index'

@main.route('/static/source')
def get_source(source):
    return source

main.py
import os
from flask_script import Manager, Shell
from flask_migrate import Migrate
from entity import *
from flasky import create_app


config_name = os.getenv('FLASK_CONFIG') or 'default'
app = create_app(config_name)
# manager = Manager(app)
#
# manager.add_command('shell', Shell(make_context=make_shell_context))
migrate = Migrate(app, db)

@app.shell_context_processor
def make_shell_context():
    return dict(app=app, db=db, User=User, Role=Role, Post=Post, Follow=Follow)



if __name__ == '__main__':
    # manager.run()
    app.run(debug=True)

templates/_macros.html
{% macro pagination_widget(pagination, endpoint) %}
<ul class="pagination">
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{% else %}#{% endif %}">
            &laquo;
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

templates/_posts.html
<ul class="posts">
    {% for post in posts %}
    <li class="post">
        <!-- <div class="post-thumbnail">
            <a href="{{ url_for('.user', username=post.author.username) }}">
            </a>
        </div> -->
        <div class="post-content">
            <div class="post-title">
                <a href="{{ url_for('.post', post_id=post.id) }}">
                    Title: {{ post.title }}
                </a>
            </div>
            <div class="post-body">{{ post.body }}</div>
            <div>
                <a href="{{ url_for('.user', username=post.author.username) }}">
                    {{ post.author.username }}
                </a>
                发布于{{ moment(post.timestamp).fromNow() }}
            </div>
        </div>
    </li>
    {% endfor %}
</ul>

templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Flasky{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
{% endblock %}



{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Flasky</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">Home</a></li>
                {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('main.user', username=current_user.username) }}">Profile</a></li>
                {% endif %}
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('auth.change_password') }}">Change Password</a></li>
                        <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                    </ul>
                </li>
                {% else %}
                <li><a href="{{ url_for('auth.login') }}">Log In</a></li>
                {% endif %}
            </ul>



        </div>
    </div>
</div>
{% endblock %}


{% block content %}
{% block message %}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
              <p>{{ message }}</p>
            {% endfor %}
        {% endif %}
    {% endwith %}
{% endblock %}

<div class="container">
    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}

<script src="{{ url_for('static', filename='jquery-3.3.1.js') }}"></script>

<script> {% include "js/util.js" %} </script>

{{ moment.include_moment() }}
{% endblock %}

templates/edit_profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Flasky - Edit Profile{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Edit Your Profile</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}Flasky{% endblock %}



{% block page_content %}
<div class="page-header">
    <h1>Hello, {% if current_user.is_authenticated %}{{ current_user.username }}{% else %}Stranger{% endif %}!</h1>
</div>
<div>
    {{ wtf.quick_form(form) }}
</div>

{% set posts = pagination.items %}
{% include '_posts.html' %}

{% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination, '.index') }}
</div>
{% endif %}
{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}

templates/post.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block head %}
{{ super() }}
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='link.css') }}">
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='post.css') }}">

{% endblock %}

{% block page_content %}

<div class='other'>
    <div class='author'>
        <p>作者简介</p>
        <hr>
        <a href="{{ url_for('.user', username=post.author.username) }}">
            {{ post.author.username }}
        </a>
    </div>
</div>

<div class="post">
    <div class='post-content'>
        <h1>Title: {{ post.title }}</h1>

        <p>{{ post.body }}<p>
        <div>
            <a href="{{ url_for('.user', username=post.author.username) }}">
                {{ post.author.username }}
            </a>
            发布于{{ moment(post.timestamp).fromNow() }}
        </div>
    </div>
    <hr>

    <div class="comment_area">
        <div class="comments">
            <ul>
                <li class='comment-count'>
                    <p>comments count: {{post.comments.count()}}</p>
                </li>

                {% for comment in pagination.items %}
                    <li class="comment" id="comment{{comment.id}}">
                        <div>
                            <div class="comment-time">
                                发布于{{ moment(comment.timestamp).fromNow() }}
                            </div>
                            <div class="comment-profile">
                                <line class="comment-author">
                                    <a href="{{ url_for('.user', username=comment.author.username) }}">
                                        &nbsp; &nbsp; {{ comment.author.username }}
                                    </a>
                                    {% if comment.author.id == post.author.id %}
                                        <line style="color:gray">(作者)</line>
                                    {% endif %}
                                </line>

                                {% if comment.target %}
                                    <line style="color:gray">&nbsp;回复&nbsp;</line>
                                    <line class="comment-target">
                                        <a href="{{ url_for('.user', username=comment.target.username) }}">
                                            &nbsp; &nbsp; {{ comment.target.username }}
                                        </a>
                                    </line>
                                {% endif %}
                            </div>

                            <div class="comment-content">{{ comment.body }}</div>

                            <div class="comment-interact">

                                <line>xx</line>
                                <line class="interact">
                                    <button class="response">回复</button>
                                </line>
                            </div>

                            <form class="comment_user_form comment_form form form-horizontal" method="post" role="form"
                                    action="{{url_for('.comment', target_id=comment.id,
                                            post_id=post.id)}}" >
                                {{ form.hidden_tag() }}
                                {{ wtf.form_errors(form, hiddens="only") }}
                                {% set placeholder = '回复 '+comment.author.username|string %}
                                {{ wtf.form_field(form.content, placeholder=placeholder) }}
                                {{ wtf.form_field(form.submit, class="comment-submit") }}
                                <button class="cancle_comment">cancle</button>
                            </form>

                        </div>

                    </li>
                {% endfor %}
            </ul>
        </div>
        {% if pagination %}
            <div class="pagination_area">
                {{ macros.pagination_widget(pagination, '.post', post_id=post.id) }}
            </div>
        {% endif %}

    </div>



    <div>
        <form class="comment_form form form-horizontal" method="post" role="form"
                action="{{url_for('.comment', post_id=post.id)}}" >
            {{ form.hidden_tag() }}
            {{ wtf.form_errors(form, hiddens="only") }}

            {{ wtf.form_field(form.content) }}
            {{ wtf.form_field(form.submit, class="comment-submit") }}
        </form>
    </div>


</div>



{% endblock %}

{% block scripts %}
    {{ super() }}

    <script> {% include "js/post.js" %} </script>

{% endblock %}

templates/user.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block title %}Flasky - {{ user.username }}{% endblock %}

{% block head %}
{{ super() }}
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='user.css') }}">
{% endblock %}
{% block page_content %}

<div id="social">
    <p>关注了：{{user.followeds.count()|string}}人</p>
    <p>关注者：{{user.followers.count()|string}}人</p>
    {% if user.id != current_user.id %}
        {% if current_user.is_following(user) %}
            <button class="cancel_follow">取消关注</button>
        {% else %}
            <button class="follow">关注</button>
        {% endif %}
    {% endif %}
</div>


<div class="base">
    <div class="edit">
        {% if user == current_user %}
            <a class="btn btn-default" href="{{ url_for('.edit_profile') }}">
                Edit Profile
            </a>
        {% endif %}
    </div>

    <h1>{{ user.username }}</h1>

    <div class="profile">
        <ul>
            <li class="name">
                {% if user.name %}Name: {{ user.name }}{% endif %}
            </li>
            <li class="location">
                {% if user.location %}
                    Location:
                    <a href="http://maps.google.com/?q={{ user.location }}">
                        {{ user.location }}
                    </a>
                {% endif %}
            </li>
            <li class="about_me">
                {% if user.about_me %}
                    about me: {{ user.about_me }}
                {% endif %}
            </li>
            <li class="regist_time">
                Regist Time: {{ moment(user.regist_time).format('L') }}
            </li>
            <li class="last_seen">
                Last seen {{ moment(user.last_seen).fromNow() }}.
            </li>
            <li class="post_count">
                {{ user.posts.count() }} blog posts.
            </li>
        </ul>
    </div>

    <h3>Posts by {{ user.username }}</h3>

    {% set posts = pagination.items %}
    {% include '_posts.html' %}
    {% if pagination %}
    <div class="pagination">
        {{ macros.pagination_widget(pagination, '.user', username=user.username) }}
    </div>
    {% endif %}


</div>

{% endblock %}


{% block scripts %}
    {{ super() }}
    <script> {% include "js/user.js" %} </script>
{% endblock %}